version: '3'
services:

  frontend:
    image: chigui794/exam1-frontend:1.1.1
    container_name: exam1-frontend
    ports:
      - "8085:80"
    restart: always
    networks:
      - exam1  # Asignar el servicio a la red exam1  

  backend:
    image: chigui794/exam1-backend:1.1.0
    container_name: exam1-backend
    ports:
      - "3500:3500"
    restart: always
    networks:
      - exam1  # Asignar el servicio a la red exam1

